const initialAnimals = [
  { id: 1, name: "Buddy", age: 3, species: "Dog", breed: "Labrador", color: "Golden", description: "Friendly and playful.", photo: "https://images.unsplash.com/photo-1529831129093-0fa4866281ee?q=80&w=1974&auto=format&fit=crop" },
  { id: 2, name: "Milo", age: 2, species: "Cat", breed: "Siamese", color: "Cream", description: "Loves cuddles.", photo: "https://images.unsplash.com/photo-1568152950566-c1bf43f4ab28?q=80&w=1965&auto=format&fit=crop" },
  { id: 3, name: "Charlie", age: 1, species: "Dog", breed: "Beagle", color: "Brown", description: "Energetic and curious.", photo: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=1974&auto=format&fit=crop" },
  { id: 4, name: "Luna", age: 4, species: "Rabbit", breed: "Mini Lop", color: "White", description: "Calm and affectionate.", photo: "https://images.unsplash.com/photo-1533514114760-4389f572ae26?q=80&w=1936&auto=format&fit=crop" },
  { id: 5, name: "Lucy", age: 2, species: "Cat", breed: "Persian", color: "Grey", description: "Independent and elegant.", photo: "https://images.unsplash.com/photo-1585137173132-cf49e10ad27d?q=80&w=1972&auto=format&fit=crop" },
  { id: 6, name: "Daisy", age: 1, species: "Dog", breed: "Poodle", color: "White", description: "Loyal and intelligent.", photo: "https://images.unsplash.com/photo-1555325084-b068599743c9?q=80&w=1950&auto=format&fit=crop" },
  { id: 7, name: "Max", age: 5, species: "Dog", breed: "German Shepherd", color: "Black and Tan", description: "Protective and loyal.", photo: "https://via.placeholder.com/150" },
  { id: 8, name: "Bella", age: 3, species: "Cat", breed: "Maine Coon", color: "Brown", description: "Affectionate and gentle.", photo: "https://via.placeholder.com/150" },
  { id: 9, name: "Rocky", age: 4, species: "Dog", breed: "Bulldog", color: "Brindle", description: "Calm and courageous.", photo: "https://via.placeholder.com/150" },
  { id: 10, name: "Cleo", age: 2, species: "Cat", breed: "Bengal", color: "Spotted", description: "Energetic and vocal.", photo: "https://via.placeholder.com/150" },
  { id: 11, name: "Simba", age: 1, species: "Rabbit", breed: "Lionhead", color: "Golden", description: "Curious and fluffy.", photo: "https://via.placeholder.com/150" },
  { id: 12, name: "Shadow", age: 3, species: "Cat", breed: "Bombay", color: "Black", description: "Mysterious and sleek.", photo: "https://via.placeholder.com/150" },
  { id: 13, name: "Buster", age: 6, species: "Dog", breed: "Boxer", color: "Fawn", description: "Playful and energetic.", photo: "https://via.placeholder.com/150" },
  { id: 14, name: "Ginger", age: 4, species: "Cat", breed: "Abyssinian", color: "Ruddy", description: "Agile and lively.", photo: "https://via.placeholder.com/150" },
  { id: 15, name: "Poppy", age: 1, species: "Rabbit", breed: "Dutch", color: "Black and White", description: "Sweet and docile.", photo: "https://via.placeholder.com/150" },
  { id: 16, name: "Rex", age: 2, species: "Dog", breed: "Dalmatian", color: "Black and White", description: "Energetic and unique.", photo: "https://via.placeholder.com/150" },
  { id: 17, name: "Coco", age: 3, species: "Cat", breed: "Ragdoll", color: "Cream and Brown", description: "Relaxed and loving.", photo: "https://via.placeholder.com/150" },
  { id: 18, name: "Nala", age: 2, species: "Rabbit", breed: "Rex", color: "Grey", description: "Soft and gentle.", photo: "https://via.placeholder.com/150" },
  { id: 19, name: "Zeus", age: 5, species: "Dog", breed: "Husky", color: "Grey and White", description: "Strong and adventurous.", photo: "https://via.placeholder.com/150" },
  { id: 20, name: "Mittens", age: 1, species: "Cat", breed: "American Shorthair", color: "Tabby", description: "Curious and playful.", photo: "https://via.placeholder.com/150" },
  { id: 21, name: "Fiona", age: 4, species: "Rabbit", breed: "Angora", color: "White", description: "Fluffy and elegant.", photo: "https://via.placeholder.com/150" },
  { id: 22, name: "Hunter", age: 3, species: "Dog", breed: "Golden Retriever", color: "Golden", description: "Friendly and dependable.", photo: "https://via.placeholder.com/150" },
  { id: 23, name: "Lola", age: 2, species: "Cat", breed: "Scottish Fold", color: "Blue", description: "Quiet and affectionate.", photo: "https://via.placeholder.com/150" },
  { id: 24, name: "Pepper", age: 1, species: "Rabbit", breed: "Holland Lop", color: "Black", description: "Playful and cuddly.", photo: "https://via.placeholder.com/150" },
  { id: 25, name: "Oscar", age: 2, species: "Dog", breed: "Cocker Spaniel", color: "Golden", description: "Gentle and loyal.", photo: "https://via.placeholder.com/150" },
  { id: 26, name: "Smokey", age: 4, species: "Cat", breed: "Russian Blue", color: "Grey", description: "Calm and regal.", photo: "https://via.placeholder.com/150" },
  { id: 27, name: "Bambi", age: 3, species: "Rabbit", breed: "Netherland Dwarf", color: "Brown", description: "Small and lively.", photo: "https://via.placeholder.com/150" },
  { id: 28, name: "Duke", age: 5, species: "Dog", breed: "Rottweiler", color: "Black and Tan", description: "Confident and watchful.", photo: "https://via.placeholder.com/150" },
  { id: 29, name: "Whiskers", age: 1, species: "Cat", breed: "Turkish Angora", color: "White", description: "Elegant and curious.", photo: "https://via.placeholder.com/150" },
  { id: 30, name: "Hazel", age: 2, species: "Rabbit", breed: "Harlequin", color: "Orange and Black", description: "Charming and cheerful.", photo: "https://via.placeholder.com/150" },
  { id: 31, name: "Riley", age: 3, species: "Dog", breed: "Border Collie", color: "Black and White", description: "Intelligent and active.", photo: "https://via.placeholder.com/150" },
  { id: 32, name: "Toby", age: 2, species: "Dog", breed: "Shih Tzu", color: "White and Brown", description: "Affectionate and alert.", photo: "https://via.placeholder.com/150" },
  { id: 33, name: "Sassy", age: 1, species: "Cat", breed: "Oriental Shorthair", color: "Lilac", description: "Vocal and quirky.", photo: "https://via.placeholder.com/150" },
  { id: 34, name: "Willow", age: 4, species: "Rabbit", breed: "Satin", color: "Brown", description: "Calm and silky.", photo: "https://via.placeholder.com/150" },
  { id: 35, name: "Jake", age: 5, species: "Dog", breed: "Corgi", color: "Red and White", description: "Friendly and adventurous.", photo: "https://via.placeholder.com/150" },
  { id: 36, name: "Mango", age: 2, species: "Cat", breed: "Manx", color: "Orange", description: "Energetic and playful.", photo: "https://via.placeholder.com/150" },
  { id: 37, name: "Mocha", age: 2, species: "Cat", breed: "Birman", color: "Cream", description: "Sweet and loving.", photo: "https://via.placeholder.com/150" },
  { id: 38, name: "Ace", age: 4, species: "Dog", breed: "Doberman", color: "Black", description: "Alert and strong.", photo: "https://via.placeholder.com/150" },
  { id: 39, name: "Peanut", age: 1, species: "Hamster", breed: "Syrian", color: "Brown", description: "Small and quick.", photo: "https://via.placeholder.com/150" },
  { id: 40, name: "Kiwi", age: 2, species: "Bird", breed: "Parakeet", color: "Green", description: "Chirpy and cheerful.", photo: "https://via.placeholder.com/150" },
  { id: 41, name: "Tiger", age: 3, species: "Cat", breed: "Bengal", color: "Orange", description: "Wild and curious.", photo: "https://via.placeholder.com/150" },
  { id: 42, name: "Maple", age: 2, species: "Dog", breed: "Chihuahua", color: "Tan", description: "Tiny but fierce.", photo: "https://via.placeholder.com/150" },
  { id: 43, name: "Echo", age: 1, species: "Rabbit", breed: "Mini Rex", color: "Blue", description: "Quiet and soft.", photo: "https://via.placeholder.com/150" },
  { id: 44, name: "Bingo", age: 4, species: "Dog", breed: "Australian Shepherd", color: "Merle", description: "Smart and agile.", photo: "https://via.placeholder.com/150" },
  { id: 45, name: "Pumpkin", age: 2, species: "Cat", breed: "Exotic Shorthair", color: "Orange", description: "Squishy and sweet.", photo: "https://via.placeholder.com/150" },
  { id: 46, name: "Snowball", age: 1, species: "Rabbit", breed: "English Angora", color: "White", description: "Fluffy and shy.", photo: "https://via.placeholder.com/150" },
  { id: 47, name: "Storm", age: 3, species: "Dog", breed: "Weimaraner", color: "Silver", description: "Loyal and sleek.", photo: "https://via.placeholder.com/150" },
  { id: 48, name: "Twinkle", age: 2, species: "Cat", breed: "Tonkinese", color: "Champagne", description: "Affectionate and playful.", photo: "https://via.placeholder.com/150" },
  { id: 49, name: "Nugget", age: 1, species: "Hamster", breed: "Dwarf", color: "Cream", description: "Tiny and adorable.", photo: "https://via.placeholder.com/150" },
  { id: 50, name: "Sky", age: 2, species: "Bird", breed: "Cockatiel", color: "Yellow", description: "Sings all day.", photo: "https://via.placeholder.com/150" },
  { id: 51, name: "Ruby", age: 3, species: "Dog", breed: "Vizsla", color: "Rust", description: "Gentle and fast.", photo: "https://via.placeholder.com/150" },
  { id: 52, name: "Ash", age: 4, species: "Cat", breed: "Chartreux", color: "Blue", description: "Calm and wise.", photo: "https://via.placeholder.com/150" },
  { id: 53, name: "Toffee", age: 1, species: "Rabbit", breed: "Flemish Giant", color: "Tan", description: "Big and cuddly.", photo: "https://via.placeholder.com/150" },
  { id: 54, name: "Diesel", age: 5, species: "Dog", breed: "Mastiff", color: "Fawn", description: "Massive and mellow.", photo: "https://via.placeholder.com/150" },
  { id: 55, name: "Oreo", age: 2, species: "Cat", breed: "Tuxedo", color: "Black and White", description: "Stylish and funny.", photo: "https://via.placeholder.com/150" },
  { id: 56, name: "Buttons", age: 1, species: "Rabbit", breed: "Lop", color: "Grey", description: "Floppy-eared and shy.", photo: "https://via.placeholder.com/150" },
  { id: 57, name: "Apollo", age: 4, species: "Dog", breed: "Great Dane", color: "Black", description: "Tall and noble.", photo: "https://via.placeholder.com/150" },
  { id: 58, name: "Pearl", age: 3, species: "Cat", breed: "Snowshoe", color: "White and Grey", description: "Graceful and kind.", photo: "https://via.placeholder.com/150" },
  { id: 59, name: "Sprout", age: 1, species: "Hamster", breed: "Roborovski", color: "Grey", description: "Tiny and fast.", photo: "https://via.placeholder.com/150" },
  { id: 60, name: "Sunny", age: 2, species: "Bird", breed: "Canary", color: "Bright Yellow", description: "Happy singer.", photo: "https://via.placeholder.com/150" },
  { id: 61, name: "Scout", age: 3, species: "Dog", breed: "Terrier", color: "White", description: "Brave and energetic.", photo: "https://via.placeholder.com/150" },
  { id: 62, name: "Velvet", age: 2, species: "Cat", breed: "British Shorthair", color: "Lilac", description: "Chill and plush.", photo: "https://via.placeholder.com/150" },
  { id: 63, name: "Fuzz", age: 1, species: "Rabbit", breed: "Jersey Wooly", color: "Brown", description: "Soft and fluffy.", photo: "https://via.placeholder.com/150" },
  { id: 64, name: "Jasper", age: 4, species: "Dog", breed: "Basset Hound", color: "Tri-color", description: "Loyal and low.", photo: "https://via.placeholder.com/150" },
  { id: 65, name: "Misty", age: 3, species: "Cat", breed: "Himalayan", color: "Cream and Grey", description: "Elegant and fluffy.", photo: "https://via.placeholder.com/150" },
  { id: 66, name: "Bubbles", age: 1, species: "Rabbit", breed: "Mini Lop", color: "White", description: "Gentle and clean.", photo: "https://via.placeholder.com/150" },
  { id: 67, name: "Thor", age: 5, species: "Dog", breed: "Akita", color: "Red", description: "Strong and silent.", photo: "https://via.placeholder.com/150" },
  { id: 68, name: "Zoe", age: 2, species: "Cat", breed: "Sphynx", color: "Pink", description: "Hairless and cuddly.", photo: "https://via.placeholder.com/150" },
  { id: 69, name: "Cinnamon", age: 1, species: "Hamster", breed: "Teddy Bear", color: "Golden", description: "Chubby and cute.", photo: "https://via.placeholder.com/150" },
  { id: 70, name: "Blaze", age: 2, species: "Bird", breed: "Lovebird", color: "Red and Green", description: "Passionate singer.", photo: "https://via.placeholder.com/150" },
  { id: 71, name: "Tank", age: 4, species: "Dog", breed: "Bulldog", color: "Tan", description: "Tough but sweet.", photo: "https://via.placeholder.com/150" },
  { id: 72, name: "Lacey", age: 3, species: "Cat", breed: "Ragamuffin", color: "Cream", description: "Lap lover.", photo: "https://via.placeholder.com/150" },
  { id: 73, name: "Muffin", age: 1, species: "Rabbit", breed: "Havana", color: "Chocolate", description: "Sweet and still.", photo: "https://via.placeholder.com/150" },
  { id: 74, name: "Hawk", age: 2, species: "Dog", breed: "Whippet", color: "Grey", description: "Fast and focused.", photo: "https://via.placeholder.com/150" },
  { id: 75, name: "Clover", age: 3, species: "Cat", breed: "LaPerm", color: "White", description: "Curly cutie.", photo: "https://via.placeholder.com/150" },
  { id: 76, name: "Cloud", age: 1, species: "Rabbit", breed: "Mini Satin", color: "White", description: "Light and silent.", photo: "https://via.placeholder.com/150" },
  { id: 77, name: "Dino", age: 5, species: "Dog", breed: "Newfoundland", color: "Black", description: "Giant sweetheart.", photo: "https://via.placeholder.com/150" },
  { id: 78, name: "Tinker", age: 2, species: "Cat", breed: "Munchkin", color: "Tabby", description: "Short and sassy.", photo: "https://via.placeholder.com/150" },
  { id: 79, name: "Gizmo", age: 1, species: "Hamster", breed: "Campbell", color: "White and Brown", description: "Tiny explorer.", photo: "https://via.placeholder.com/150" },
  { id: 80, name: "Rio", age: 2, species: "Bird", breed: "Macaw", color: "Blue and Gold", description: "Loud and lovely.", photo: "https://via.placeholder.com/150" },
  { id: 81, name: "Diesel", age: 3, species: "Dog", breed: "Boxer", color: "Brindle", description: "Muscular and fun.", photo: "https://via.placeholder.com/150" },
  { id: 82, name: "Lily", age: 2, species: "Cat", breed: "Oriental", color: "Black", description: "Graceful and lean.", photo: "https://via.placeholder.com/150" },
  { id: 83, name: "Snickers", age: 1, species: "Rabbit", breed: "Checkered Giant", color: "Black and White", description: "Big and bouncy.", photo: "https://via.placeholder.com/150" },
  { id: 84, name: "Bolt", age: 4, species: "Dog", breed: "Greyhound", color: "Grey", description: "Zoom master.", photo: "https://via.placeholder.com/150" },
  { id: 85, name: "Marble", age: 3, species: "Cat", breed: "Devon Rex", color: "Marbled", description: "Clever and cuddly.", photo: "https://via.placeholder.com/150" },
  { id: 86, name: "Fluffy", age: 1, species: "Rabbit", breed: "Angora", color: "Cream", description: "Ball of fur.", photo: "https://via.placeholder.com/150" },
  { id: 87, name: "Titan", age: 5, species: "Dog", breed: "Alaskan Malamute", color: "Grey and White", description: "Powerful and proud.", photo: "https://via.placeholder.com/150" },
  { id: 88, name: "Penny", age: 2, species: "Cat", breed: "Calico", color: "Tricolor", description: "Colorful personality.", photo: "https://via.placeholder.com/150" },
  { id: 89, name: "Popcorn", age: 1, species: "Hamster", breed: "Winter White", color: "White", description: "Bouncy and fast.", photo: "https://via.placeholder.com/150" },
  { id: 90, name: "Whistle", age: 2, species: "Bird", breed: "Finch", color: "Grey", description: "Softly sings.", photo: "https://via.placeholder.com/150" },
  { id: 91, name: "Nova", age: 4, species: "Dog", breed: "Pomeranian", color: "Orange", description: "Puffy and proud.", photo: "https://via.placeholder.com/150" },
  { id: 92, name: "Inky", age: 3, species: "Cat", breed: "Bombay", color: "Black", description: "Night panther.", photo: "https://via.placeholder.com/150" },
  { id: 93, name: "Misty", age: 1, species: "Rabbit", breed: "Mini Lop", color: "Lilac", description: "Soft soul.", photo: "https://via.placeholder.com/150" },
  { id: 94, name: "Bear", age: 5, species: "Dog", breed: "Saint Bernard", color: "Brown and White", description: "Gentle giant.", photo: "https://via.placeholder.com/150" },
  { id: 95, name: "Cali", age: 2, species: "Cat", breed: "Calico", color: "Orange and Black", description: "Fiery fluff.", photo: "https://via.placeholder.com/150" },
  { id: 96, name: "Jelly", age: 1, species: "Hamster", breed: "Syrian", color: "Gold", description: "Soft jellybean.", photo: "https://via.placeholder.com/150" },
  { id: 97, name: "Spark", age: 2, species: "Bird", breed: "Parrot", color: "Red", description: "Talks a lot.", photo: "https://via.placeholder.com/150" },
  { id: 98, name: "Diesel", age: 3, species: "Dog", breed: "Pitbull", color: "Grey", description: "Strong and snuggly.", photo: "https://via.placeholder.com/150" },
  { id: 99, name: "Puma", age: 2, species: "Cat", breed: "Savannah", color: "Spotted", description: "Wild look.", photo: "https://via.placeholder.com/150" },
  { id: 100, name: "Patches", age: 1, species: "Rabbit", breed: "Dwarf Hotot", color: "White with black eye rings", description: "Tiny and adorable.", photo: "https://via.placeholder.com/150" }
];

export default initialAnimals;
